<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotVVM.AutoUI" Version="5.0.0-preview09-final" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.9">
    </PackageReference>
    <PackageReference Include="MySql.EntityFrameworkCore" Version="10.0.7" />
  </ItemGroup>

</Project>
